music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    #/music/34/
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),

    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

swebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models


class Album(models.Model):

    artist = models.CharField(max_length=250)

    album_title = models.CharField(max_length=350)

    genre = models.CharField(max_length=250)

    album_logo = models.CharField(max_length=350)

    def __str__(self):
        return self.album_title + ' _ ' + self.artist


class Songs(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    File_Type = models.CharField(max_length=20)

    song_title = models.CharField(max_length=350)

    is_fav=models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

umbrella/models.py
from django.db import models


class Umbrella_dep(models.Model):

  department=models.CharField(max_length=250)

  def __str__(self):
       return self.department

class Sub_department(models.Model):

    umbrella_b = models.ForeignKey(Umbrella_dep, on_delete=models.CASCADE)
    technology=models.CharField(max_length=40, default='SOME STRING')

    def __str__(self):
        return self.technology

class D_employee(models.Model):

        sub_department = models.ForeignKey(Sub_department, on_delete=models.CASCADE)

        name=models.CharField(max_length=250)
        age=models.CharField(max_length=20)
        mobile_no=models.CharField(max_length=20)

music/views.py
from django.http import HttpResponse
from .models import Album,Songs
#from django.template import loader
from django.shortcuts import render,get_object_or_404
from django.http import Http404

def index(request):
    all_album=Album.objects.all()
    #template1=loader.get_template('music/index.html')
    context={
        'all_album':all_album,
    }

    return render(request, 'index.html', context)


def details(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    return render(request, 'details.html', {'album':album})

def favorite(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    try:
         selected_song=album.songs_set.get(pk=request.post['song'])

    except(KeyError, Songs.DoesNotExist):
        return render(request, 'details.html',{
            'album':album,
            'error_message':"you didn,t select valid song"
        })

    else:
        selected_song.is_fav=True
        selected_song.save()

umbrella/views.py
from django.shortcuts import render

# Create your views here.

music/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Viberr</title>
{%load staticfiles%}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

     <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
     <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

     <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
     <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href ="{% url 'music:index' %}"> Viberr</a>

        </div>

           <div class="collapse navbar-collapse" id="topNavBar" >

            <ul class="nav navbar-nav">

                <li class="active" >

                  <a href ="{% url 'music:index' %}">
                      <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums

                  </a>

                </li>
                <li class="">

                  <a href ="">
                      <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Songs

                  </a>

                </li>


            </ul>
               <form class="navbar-form navbar-left" role="search" method="get" action="#">
                   <div>
                       <input type="text" class="form-control" name="q" value="">
                   </div>
                   <button type="submit" class="btn btn-default">Search</button>
               </form>
               <ul class="nav navbar-nav navbar-right">
                   <li class="">
                       <a href="#">
                         <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                       </a>
                   </li>
                   <li class="">
                       <a href="#">
                         <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                       </a>
                   </li>
               </ul>
        </div>

    </div>


</nav>
{%block body%}
{%endblock%}
</body>
</html>

music/templates/details.html
{% extends 'base.html' %}
{%block body%}
<h2>{{album.album_title}}</h2>

  {% if error_message %}

     <p> <strong> {{error_message}}</strong></p>

  {%endif%}

 <form action="{%url 'music:favorite' album.id %}" method="post">
    {%csrf_token%}

      {% for song in album.songs_set.all %}

          <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}" />
          <label for="song{{forloop.counter}}">
              {{song.song_title}}
              {%if song.is_favorite %}
                 <h2>this is your fav song</h2>
              {%endif%}
          </label>
      {%endfor%}
      <input type="submit" value="favorite">
 </form>
{% endblock%}

music/templates/index.html
{% extends 'base.html' %}
{%block body%}
  <ul>
     {% for album in all_album%}
         <li><a href = "{% url 'music:details' album.id%}">{{album.album_title}}</a></li>
     {% endfor %}
  </ul>
{% endblock%}